# Site configuration for GitHub Pages with Hacker theme
title: "Gary | Full-Stack Developer"
description: "Interested in building scalable, production-ready systems at the intersection of web, data, and emerging technologies."

# Theme configuration
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional: Show download button (set to false since this is a portfolio, not a downloadable project)
show_downloads: false

# Optional: Add Google Analytics (uncomment and add your tracking ID if needed)
# google_analytics: YOUR_TRACKING_ID_HERE

# GitHub repository information (GitHub Pages will auto-populate these, but you can override)
github:
  repository_name: "myopicOracle"
  owner_name: "myopicOracle"

# Site settings
url: "https://myopicOracle.github.io"
baseurl: "/myopicOracle" # Change this to your repository name if it's not your main GitHub Pages site

# Markdown processor
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - __stash__